type ComponentGalleryClassName =
  | "cardGrid"
  | "contextHeading"
  | "contextSection"
  | "example"
  | "exampleDescription"
  | "exampleGrid"
  | "exampleHeader"
  | "exampleTitle"
  | "exampleWide"
  | "gallery"
  | "galleryIntro"
  | "inputGrid"
  | "introCopy"
  | "preview"
  | "section"
  | "sectionDescription"
  | "sectionHeader"
  | "sectionTitle"
  | "shellHost"
  | "stage"
  | "stageColumn"
  | "stageCopy"
  | "stageRow"
  | "storyboardGrid"
  | "surface"
  | "surfaceBase"
  | "surfaceCanvas"
  | "surfaceCard"
  | "surfaceElevated"
  | "surfaceGrid"
  | "surfaceLabel"
  | "surfacePanel"
  | "validationStack"
  | "verticalDivider";

declare const styles: Readonly<Record<ComponentGalleryClassName, string>>;

export default styles;
