type ProductionClassName =
  | "inspectorBody"
  | "inspectorDescription"
  | "inspectorHeader"
  | "inspectorHeading"
  | "inspectorSection"
  | "notesEditor"
  | "notesHeader"
  | "notesHeading"
  | "notesPanel"
  | "notesPrompt"
  | "objectActions"
  | "objectCard"
  | "objectContent"
  | "objectDescription"
  | "objectHeadingRow"
  | "objectMetadata"
  | "objectPreview"
  | "objectTitle"
  | "objectTitleAction"
  | "propertyControl"
  | "propertyCopy"
  | "propertyDescription"
  | "propertyLabel"
  | "propertyRow"
  | "propertySourceRow"
  | "scopeLabel"
  | "sequenceNumber"
  | "statusBadge"
  | "storyboardCard"
  | "storyboardPreview"
  | "timelineLabel"
  | "validation-blocking"
  | "validation-warning"
  | "validationAction"
  | "validationCopy"
  | "validationItem"
  | "validationSeverity"
  | "visuallyHidden";

declare const styles: Readonly<Record<ProductionClassName, string>>;

export default styles;
